# This is a basic workflow to help you get started with Actions

name: Wiki

# Controls when the action will run. 
on:
  gollum

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.repository.full_name }}.wiki
          ref: ${{ github.event.pages[0].sha }}
          fetch-depth: 2
      - name: Slack
        run: |
          url=${HTML_URL}/_compare/$(git rev-parse HEAD^)...$(git rev-parse HEAD)
          curl -X POST --data-urlencode \
            "payload={\"username\": \"GithubActiosBot\", \"text\": \"Wiki ${ACTION}: <${HTML_URL}|${TITLE}ページ>  <${url}|diff> - ${COMMIT_MESSAGE}\"}" \
            ${WEBHOOK_URL}
        env:
          ACTION: ${{ github.event.pages[0].action }}
          TITLE: ${{ github.event.pages[0].title }}
          HTML_URL: ${{ github.event.pages[0].html_url }}
          COMMIT_MESSAGE: ${{ github.event.pages[0].message }}
          WEBHOOK_URL: ${{ secrets.WIKI_SLACK_WEBHOOK }}
